site_name: Notes 
site_url: https://anirudh-s-kumar.github.io/notes/
repo_name: Anirudh-S-Kumar/notes
repo_url: https://github.com/Anirudh-S-Kumar/notes
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    #- navigation.instant
    #- navigation.instant.prefetch
    #- navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow  
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - 'css/custom_list.css'

plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


nav:
  - Foundations of Finance:
    - Time Value of Money: ff/time_value_money.md

  - Computer Graphics:
    - index: cg/index.md
    - Curves: cg/curves.md
    - Surfaces and Volumes: cg/surfaces.md
    - Mesh: cg/mesh.md