site_name: Compute Graphics Notes 
site_url: https://anirudh-s-kumar.github.io/cg-notes/
repo_name: Anirudh-S-Kumar/cg-notes
repo_url: https://github.com/Anirudh-S-Kumar/cg-notes
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
  #  - navigation.tabs
  #  - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow  
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

    
extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - 'css/custom_list.css'

plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


nav:
  - Curves: curves.md
  - Surfaces and Volumes: surfaces_volumes.md
  - Mesh: mesh.md
  - Geometric Transformations: transformations.md
  - Viewing and Projections: viewing.md
  - Colors: colors.md
  - Lighting and Shading: lighting.md
  - Ray Tracing : ray_tracing.md
  - Advanced Ray Tracing: advanced_ray_tracing.md
  - Rasterization: rasterization.md
  - Texture Mapping: texture_mapping.md
  - Visibility Determination: visibility_determination.md
  - Implicit Modelling and Reconstruction: implicit_modelling.md
  - Animation: animations.md
  - Parametric Curves: parametric_curves.md
